// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"gomod/internal/api"
	"gomod/internal/module/luckywheel"
	"gomod/internal/module/sign_in"
	"gomod/internal/module/task"
	"gomod/internal/module/task/model"
	"gomod/pkg/xmysql"
	"gomod/pkg/xredis"
)

// Injectors from wire.go:

func InitApi() (*api.Api, error) {
	client, err := xredis.NewRdsClient()
	if err != nil {
		return nil, err
	}
	db, err := xmysql.NewDB()
	if err != nil {
		return nil, err
	}
	modelModel, err := model.ModelProvider(client, db)
	if err != nil {
		return nil, err
	}
	service, err := task.ServiceProvider(modelModel)
	if err != nil {
		return nil, err
	}
	sign_inService, err := sign_in.ServiceProvider(modelModel)
	if err != nil {
		return nil, err
	}
	luckywheelService, err := luckywheel.ServiceProvider(modelModel)
	if err != nil {
		return nil, err
	}
	apiApi, err := api.ApiProvider(service, sign_inService, luckywheelService)
	if err != nil {
		return nil, err
	}
	return apiApi, nil
}
